# @scf-option  {"ignore": "true"}
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pdd-template-static-website-react-flora
  title: React and flora website
  description: Provides a react app in the SPA model using flora design system.
  tags: ["web", "html", "react", "flora", "javascript", "frontend"]
spec:
  owner: pdd-team
  type: website

  parameters:
    - $yaml: ../../../pdd-template-backstage/blob/main/backstage/scaffolder/general-info-form.yaml
    - $yaml: ./frontend-form.yaml

  steps:
    - id: sonar
      name: Initialize Sonar
      action: gb-tech:sonar-init
      input:
        component: ${{ parameters.component }}
        domain: ${{ parameters.domain }}
        system: ${{ parameters.system }}
        team: ${{ parameters.team }}

    - id: vars
      name: Load Domain Vars
      action: gb-tech:get-vars
      input:
        parameters: ${{parameters}}
        domain: ${{ parameters.domain }}
        system: ${{ parameters.system }}
        component: ${{ parameters.component }}
        sonarProjectId: ${{steps.sonar.output.projectId}}
        team: ${{ parameters.team }}
        additionalParameters:
          lifecycle: "experimental"
          hasArgocd: true
          argocdAppSelector: ${{parameters.component}}
          hasNewRelic: true
          newRelicEntityName: ${{parameters.component}}
          appPort: 3000

    - id: github-app-token
      name: Get Github App Tokens
      action: gb-tech:get-github-app-token
      input:
        accountLogin: ${{steps.vars.output.github.orgName}}

    - id: scafflater-init
      name: Init code template
      action: gb-tech:scafflater-init
      input:
        repo: "https://github.com/${{steps.vars.output.github.orgName}}/pdd-template-static-website-react-flora"
        parameters: ${{steps.vars.output.parameters}}
        config:
          githubUsername: "x-access-token"
          githubPassword: ${{ steps['github-app-token'].output.accessToken }}
          annotate: false

    - id: scafflater-init-github
      name: Configuring Github
      action: gb-tech:scafflater-init
      input:
        repo: "https://github.com/${{steps.vars.output.github.orgName}}/pdd-template-github"
        parameters: ${{steps.vars.output.parameters}}
        config:
          githubUsername: "x-access-token"
          githubPassword: ${{ steps['github-app-token'].output.accessToken }}
          annotate: false

    - id: scafflater-init-backstage
      name: Init Backstage Configuration
      action: gb-tech:scafflater-init
      input:
        repo: "https://github.com/${{steps.vars.output.github.orgName}}/pdd-template-backstage"
        parameters: ${{steps.vars.output.parameters}}
        config:
          githubUsername: "x-access-token"
          githubPassword: ${{ steps['github-app-token'].output.accessToken }}
          annotate: false

    - id: scafflater-catalog-info
      name: Generate "catalog-info.yaml"
      action: gb-tech:scafflater-add-partial
      input:
        templateName: "pdd-template-backstage"
        partial: "catalog:configure"
        parameters: ${{steps.vars.output.parameters}}
        config:
          githubUsername: "x-access-token"
          githubPassword: ${{ steps['github-app-token'].output.accessToken }}
          annotate: false

    - id: scafflater-init-infra
      name: Init Infra
      action: gb-tech:scafflater-init
      input:
        repo: "https://github.com/${{steps.vars.output.github.orgName}}/pdd-template-crossplane-aws"
        parameters: ${{steps.vars.output.parameters}}
        config:
          githubUsername: "x-access-token"
          githubPassword: ${{ steps['github-app-token'].output.accessToken }}
          annotate: false

    - id: scafflater-infra-app-role
      name: Add frontend DNS
      action: gb-tech:scafflater-add-partial
      input:
        templateName: "pdd-template-crossplane-aws"
        partial: "frontend"
        parameters: ${{steps.vars.output.parameters}}
        config:
          githubUsername: "x-access-token"
          githubPassword: ${{ steps['github-app-token'].output.accessToken }}
          annotate: false

    - id: create-repo
      name: Create repo
      action: gb-tech:initialize-repo
      input:
        owner: ${{steps.vars.output.github.orgName}}
        repo: ${{steps.vars.output.github.repoName}}
        description: ${{parameters.componentDescription}}
        type: "app-backend"
        template: ${{steps.vars.output.github.orgName}}/pdd-template-static-website-react-flora
        domain: ${{parameters.domain}}
        team: ${{parameters.team}}
        committerEmail: ${{parameters.githubUser.email}}
        committerName: ${{parameters.githubUser.displayName}}

    - id: register
      name: Register New System
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.vars.output.github.repoUrl}}/blob/main
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.vars.output.github.repoUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
